name: netflix
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  animate_do: ^3.0.2
  bloc: ^8.1.2
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  dartz: ^0.10.1
  dio: ^5.3.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  get_it: ^7.6.0
  google_fonts: ^5.1.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
